model_list:
  - model_name: qwen3:0.6b
    litellm_params:
      model: ollama/qwen3:0.6b
      api_base: http://ollama:11434

litellm_settings:
  telemetry: false
  turn_off_message_logging: true

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  store_model_in_db: true
